### ISSUE TITLE
I'm interested to see what you do here

### ISSUE THREAD

**Issue by coen-hyde** [liammclennan/resourceserver#1]
I've been exploring tighter backbone integration with node. At the moment i'm rendering the same templates server and client side. And i've thinking about how I can better unify the routes, instead of having to declare them twice (once serverside and once client side).

Another possibility i've been thinking about is pushing templates down the wire when they change.

**Comment by liammclennan** [comment]
My goals for backbone server, which I will add to the readme, is to provide an out-of-the-box server piece for backbone.js. 

What you are talking about sounds to me like a performance optimisation that comes at a cost to architectural simplicity. The simplest thing being a server that returns the same thing for any url, leaving routing + rendering to the client. Another advantage of your approach is search indexing. I have a project for that too http://spiderfish.withouttheloop.com/ ;)

Are you running backbone on the server to render your views?
