### ISSUE TITLE
OPTIONS method failed to respond.

### ISSUE THREAD

**Issue by fredyang** [liammclennan/resourceserver#4]
![image](https://f.cloud.github.com/assets/669555/105590/ad3c8840-69b9-11e2-85ee-982382fcd5bf.png)

![image](https://f.cloud.github.com/assets/669555/105605/5d13ea06-69ba-11e2-8f49-a395cf65374d.png)

![image](https://f.cloud.github.com/assets/669555/105611/aebfd28e-69ba-11e2-886b-416b60d332b9.png)

When I create an object, XHR's default behavior issue an OPTIONS method first, then issue POST metHod, the first one failed, however, chrome ignore that, and continue issue PUT method call. But firefox will fail all together if the first one fail. I think you should change to respond to OPTIONS query.

**Comment by liammclennan** [comment]
I like your suggestion and I will gladly accept a pull request. Thanks.
