### ISSUE TITLE
CoffeeScript compilation

### ISSUE THREAD

**Issue by malikoth** [liammclennan/resourceserver#8]
As indicated in my PR, I don't know node.js scarcely at all.  When starting up my resourceserver, I had to first manually compile the config.coffee and logger.coffee files to js by installing coffee-script as a global package in node, and then compiling each file individually.  Should that be part of the startup script, or did I just miss a step in setting up node somewhere?

(PS, thanks for your PluralSight video Liam, it helped me present on Backbone in a lunch&learn today.  :) )

**Comment by liammclennan** [comment]
It has been a while since I looked at this, but from memory you only need coffeescript as a local dependency and node will do the compilation on the fly when the modules are required. 

Glad you liked the Backbone course.
